import type { Settings } from '../types';
import { getProviderById } from './providersCatalog';

export interface ProviderOptimization {
  textModel: string;
  imageProvider: Settings['imageProvider'];
  imageModel: string;
  audioProvider: Settings['audioProvider'];
  audioModel: string;
  voice: string;
  providerDisplayName: string;
  description: string;
}

export const PROVIDER_OPTIMAL_DEFAULTS: Record<string, ProviderOptimization> = {
  gemini: {
    textModel: 'gemini-2.5-flash',
    imageProvider: 'gemini',
    imageModel: 'gemini-2.5-flash-image',
    audioProvider: 'gemini',
    audioModel: 'gemini-2.5-flash-preview-tts',
    voice: 'Kore',
    providerDisplayName: 'Google AI Studio (Gemini)',
    description: 'Default Recommended: Ultra-fast 2.5 Flash reasoning, high-sharpness 8K Gemini scene illustrations & natural voice TTS',
  },
  puter: {
    textModel: 'openai/gpt-5.4-nano',
    imageProvider: 'puter',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Puter AI (100% Free)',
    description: 'Zero API keys required. Free GPT-5.4 Nano, Nano Banana 2 Lite & OpenAI Audio',
  },
  pollinations: {
    textModel: 'openai',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Pollinations.ai (100% Free)',
    description: 'Fast, unlimited free tier with Nano Banana & OpenAI Audio TTS',
  },
  openai: {
    textModel: 'gpt-5.6-terra',
    imageProvider: 'openai',
    imageModel: 'dall-e-3',
    audioProvider: 'openai',
    audioModel: 'tts-1',
    voice: 'fable',
    providerDisplayName: 'OpenAI',
    description: 'GPT-5.6 Terra, DALL-E 3 creative images & expressive OpenAI TTS',
  },
  anthropic: {
    textModel: 'claude-sonnet-4-6',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Anthropic',
    description: 'Claude Sonnet 4.6 literary prose paired with instant visual generation',
  },
  deepseek: {
    textModel: 'deepseek-v4-flash',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'DeepSeek',
    description: 'DeepSeek V4 Flash high-speed reasoning with free storybook illustrations',
  },
  xai: {
    textModel: 'grok-4.3',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'xAI (Grok)',
    description: 'Grok 4.3 dynamic wit and vivid narrative intelligence',
  },
  cloudflare: {
    textModel: '@cf/zai-org/glm-5.2',
    imageProvider: 'cloudflare',
    imageModel: '@cf/black-forest-labs/flux-1-schnell',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Cloudflare Workers AI',
    description: 'GLM-5.2 on Cloudflare Edge with Flux.1 Schnell visuals',
  },
  mistral: {
    textModel: 'mistral-large-latest',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Mistral AI',
    description: 'Mistral Large 3 creative storytelling with free fast visuals',
  },
  nvidia: {
    textModel: 'meta/llama-3.1-8b-instruct',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'NVIDIA (NIM)',
    description: 'NVIDIA NIM Llama 3.1 8B router with high throughput and instant imagery',
  },
  groq: {
    textModel: 'llama-3.3-70b-versatile',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Groq Cloud',
    description: 'Ultra high-speed Llama 3.3 70B inference with free Nano Banana 2 imagery',
  },
  minimax: {
    textModel: 'minimax-m2.7',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'MiniMax AI',
    description: 'MiniMax M2.7 extended narrative continuity and memory',
  },
  kimi: {
    textModel: 'kimi-k2.5',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Moonshot (Kimi)',
    description: 'Kimi K2.5 massive 2M token context memory and worldbuilding',
  },
  alibaba: {
    textModel: 'qwen-max',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Alibaba (Qwen)',
    description: 'Qwen Max multilingual intelligence with fast visual generation',
  },
  together: {
    textModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Together AI',
    description: 'Llama 3.3 70B Instruct Turbo high-throughput router',
  },
  openrouter: {
    textModel: 'openrouter/free',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'OpenRouter',
    description: 'Auto Free Tier (:free models) with free high-resolution illustrations',
  },
  huggingface: {
    textModel: 'zai-org/GLM-5.2',
    imageProvider: 'huggingface',
    imageModel: 'black-forest-labs/FLUX.1-schnell',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Hugging Face',
    description: 'GLM-5.2 Serverless Inference with Flux.1 Schnell images',
  },
  fireworks: {
    textModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Fireworks AI',
    description: 'Fast compound Llama 3.3 70B inference with instant media generation',
  },
  z_ai: {
    textModel: 'glm-5.2',
    imageProvider: 'zai',
    imageModel: 'cogview-3-flash',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Z.AI (Zhipu)',
    description: 'GLM-5.2 intelligence and CogView-3-Flash image synthesis',
  },
  zai: {
    textModel: 'glm-5.2',
    imageProvider: 'zai',
    imageModel: 'cogview-3-flash',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Z.AI (Zhipu)',
    description: 'GLM-5.2 intelligence and CogView-3-Flash image synthesis',
  },
  cerebras: {
    textModel: 'llama-3.3-70b',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Cerebras',
    description: '1,800 tokens/sec Llama 3.3 70B with free multi-modal media generation',
  },
  cohere: {
    textModel: 'command-r-plus-08-2024',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Cohere',
    description: 'Command R+ rich narratives paired with free media generation',
  },
  siliconflow: {
    textModel: 'deepseek-ai/DeepSeek-V3',
    imageProvider: 'siliconflow',
    imageModel: 'black-forest-labs/FLUX.1-schnell',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'SiliconFlow',
    description: 'DeepSeek V3 narration paired with Flux.1 Schnell fast image generation',
  },
  inception: {
    textModel: 'mercury-2',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Inception AI',
    description: 'Mercury 2 fast reasoning with instant free media generation',
  },
  requesty: {
    textModel: 'meta-llama/llama-3.3-70b',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Requesty AI',
    description: 'Llama 3.3 70B router with instant free Nano Banana 2 media generation',
  },
  llamacpp: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Llama.cpp (Local)',
    description: 'Local C++ GGUF inference on port 8080',
  },
  ollama: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Ollama (Local)',
    description: 'Local Ollama model runner on port 11434 with auto model detection',
  },
  lmstudio: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'LM Studio (Local)',
    description: 'Local LM Studio OpenAI endpoint on port 1234',
  },
  jan: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Jan.ai (Local)',
    description: 'Local Jan Nitro server on port 1337',
  },
  vllm: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'vLLM (Local)',
    description: 'High-throughput local vLLM instance on port 8000',
  },
  sglang: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'SGLang (Local)',
    description: 'High-speed local SGLang structured inference on port 30000',
  },
  localai: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'LocalAI (Local)',
    description: 'Self-hosted LocalAI instance on port 8080',
  },
  gpt4all: {
    textModel: '(loaded model)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'GPT4All (Local)',
    description: 'Local GPT4All API server on port 4891',
  },
  local_openai_proxy: {
    textModel: '(required)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Local OpenAI Proxy',
    description: 'Custom OpenAI-compatible local proxy on port 5000',
  },
  webgpu: {
    textModel: 'LFM2.5 2.6B (default)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'WebGPU (In-Browser)',
    description: 'In-browser Chromium WebGPU runtime - 100% private with no server',
  },
  azure_openai: {
    textModel: '(deployment)',
    imageProvider: 'openai',
    imageModel: 'dall-e-3',
    audioProvider: 'openai',
    audioModel: 'tts-1',
    voice: 'fable',
    providerDisplayName: 'Azure OpenAI',
    description: 'Enterprise Azure OpenAI Service custom deployment',
  },
  aws_bedrock: {
    textModel: '(model id)',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'AWS Bedrock',
    description: 'Enterprise AWS Bedrock API gateway and models',
  },
  others: {
    textModel: 'deepseek-ai/DeepSeek-V3',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
    providerDisplayName: 'Custom / OpenAI Compatible',
    description: 'Universal OpenAI endpoint with high-speed media generation',
  },
};

/**
 * Automatically calculates and synchronizes optimal text, image, and audio models for a given provider.
 */
export function getOptimalSettingsForProvider(
  provider: string,
  _existingSettings?: Settings
): Partial<Settings> {
  const custom = PROVIDER_OPTIMAL_DEFAULTS[provider];
  if (custom) {
    return {
      textProvider: provider as any,
      textModel: custom.textModel,
      imageProvider: custom.imageProvider,
      imageModel: custom.imageModel,
      audioProvider: custom.audioProvider,
      audioModel: custom.audioModel,
      voice: custom.voice,
    };
  }

  // Fallback for extended catalog providers
  const meta = getProviderById(provider);
  return {
    textProvider: provider as any,
    textModel: meta.defaultModel || 'default-model',
    imageProvider: 'pollinations',
    imageModel: 'nanobanana-2-lite',
    audioProvider: 'pollinations',
    audioModel: 'openai-audio',
    voice: 'alloy',
  };
}
