export type ProviderCategory = 'recommended' | 'img_gen' | 'cloud' | 'router' | 'local' | 'extended';

export interface ModelOption {
  id: string;
  name: string;
  recommended?: boolean;
  badge?: string;
  isBestPerformance?: boolean;
  isFreeTier?: boolean;
}

export interface ProviderDefinition {
  id: string;
  name: string;
  category: ProviderCategory;
  badge: string;
  badgeColor: string;
  description: string;
  defaultModel: string;
  defaultEndpoint?: string;
  requiresKey: boolean;
  keyPlaceholder?: string;
  portalUrl?: string;
  freeTierInfo?: string;
  startingPrice?: string;
  apiType?: string;
  regions?: string | number;
  models: ModelOption[];
  isExtended?: boolean;
  isImageGen?: boolean;
}

// 1. Recommended: Best Flagship & Free-Tier Providers (Alphabetically Sorted)
export const RECOMMENDED_PROVIDERS: ProviderDefinition[] = [
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    category: 'recommended',
    badge: 'Best Literary Prose',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Claude Sonnet 4.6 and Claude 3.7 Sonnet for world-class narrative prose and poetic nuance.',
    defaultModel: 'claude-sonnet-4-6',
    defaultEndpoint: 'https://api.anthropic.com/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-ant-...',
    portalUrl: 'https://console.anthropic.com/settings/keys',
    freeTierInfo: 'Developer console trial credits available upon registration.',
    models: [
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6 (Best Performance)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'claude-3-7-sonnet', name: 'Claude 3.7 Sonnet (Hybrid Reasoning)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet' },
      { id: 'claude-3-haiku', name: 'Claude 3 Haiku (Instant Speed)' },
      { id: 'claude-3-opus', name: 'Claude 3 Opus (Deep Analysis)' },
    ],
  },
  {
    id: 'cerebras',
    name: 'Cerebras Cloud',
    category: 'recommended',
    badge: '1,800 tok/s Free Tier',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'Fastest wafer-scale inference engine with free 30 RPM tier for Llama 3.3 70B.',
    defaultModel: 'llama-3.3-70b',
    defaultEndpoint: 'https://api.cerebras.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'csk-...',
    portalUrl: 'https://cloud.cerebras.ai',
    freeTierInfo: 'Generous free tier with 30 requests per minute and 1M tokens/day.',
    models: [
      { id: 'llama-3.3-70b', name: 'Llama 3.3 70B (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'llama3.1-70b', name: 'Llama 3.1 70B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'llama3.1-8b', name: 'Llama 3.1 8B (Super Instant • Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare (Workers AI)',
    category: 'recommended',
    badge: '10K Neurons/Day Free',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Edge-distributed AI workers running GLM-5.2, Llama 3.3 70B, and DeepSeek R1.',
    defaultModel: '@cf/zai-org/glm-5.2',
    defaultEndpoint: 'https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1',
    requiresKey: true,
    keyPlaceholder: 'Cloudflare API Token',
    portalUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    freeTierInfo: '10,000 Neurons per day free on Cloudflare edge network.',
    models: [
      { id: '@cf/zai-org/glm-5.2', name: 'GLM-5.2 (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: '@cf/meta/llama-3.3-70b-instruct', name: 'Llama 3.3 70B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b', name: 'DeepSeek R1 Distill 32B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: '@cf/meta/llama-3.1-8b-instruct', name: 'Llama 3.1 8B Instruct (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: '@cf/mistral/mistral-7b-instruct-v0.1', name: 'Mistral 7B Instruct (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'recommended',
    badge: 'Reasoning & Best Value',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    description: 'DeepSeek V4 Flash, DeepSeek Chat (V3), and DeepSeek Reasoner (R1) direct API.',
    defaultModel: 'deepseek-v4-flash',
    defaultEndpoint: 'https://api.deepseek.com/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://platform.deepseek.com/api_keys',
    freeTierInfo: 'Affordable top-tier reasoning with free trial balance.',
    models: [
      { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash (Best Performance • Best Value)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'deepseek-chat', name: 'DeepSeek Chat V3 (Best Performance)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'deepseek-reasoner', name: 'DeepSeek Reasoner R1 (Best Reasoning)', isBestPerformance: true, badge: 'Best Reasoning' },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' },
    ],
  },
  {
    id: 'gemini',
    name: 'Google AI Studio (Gemini)',
    category: 'recommended',
    badge: 'Default • Best Multimodal',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Ultra-fast 2.5 Flash / 3.1 Flash reasoning, high-sharpness Gemini scene illustrations & natural voice TTS.',
    defaultModel: 'gemini-2.5-flash',
    defaultEndpoint: 'https://generativelanguage.googleapis.com/v1beta',
    requiresKey: true,
    keyPlaceholder: 'AIzaSy...',
    portalUrl: 'https://aistudio.google.com/app/apikey',
    freeTierInfo: '1,000 requests per day always free on Flash tier.',
    models: [
      { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'gemini-3.1-flash', name: 'Gemini 3.1 Flash (Next-Gen Preview • Free Tier)', isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro (Deep Narrative Complexity)' },
      { id: 'gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro Preview' },
      { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gemini-2.0-flash-lite', name: 'Gemini 2.0 Flash Lite (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'groq',
    name: 'Groq Cloud',
    category: 'recommended',
    badge: 'Ultra Fast (1K RPD Free)',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Blazing LPU inference speeds for Llama 3.3 70B and DeepSeek R1 Distill at 500+ tok/s.',
    defaultModel: 'llama-3.3-70b-versatile',
    defaultEndpoint: 'https://api.groq.com/openai/v1',
    requiresKey: true,
    keyPlaceholder: 'gsk_...',
    portalUrl: 'https://console.groq.com/keys',
    freeTierInfo: '1,000 requests per day always free tier.',
    models: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'llama-3.1-70b-versatile', name: 'Llama 3.1 70B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gemma2-9b-it', name: 'Gemma 2 9B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'qwen-2.5-32b', name: 'Qwen 2.5 32B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'recommended',
    badge: 'Serverless Free Tier',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    description: 'Serverless inference on Hugging Face Novita router for GLM-5.2, Llama 3.3, and Flux.',
    defaultModel: 'zai-org/GLM-5.2',
    defaultEndpoint: 'https://router.huggingface.co/novita/v1',
    requiresKey: true,
    keyPlaceholder: 'hf_...',
    portalUrl: 'https://huggingface.co/settings/tokens',
    freeTierInfo: 'Free community rate limits available.',
    models: [
      { id: 'zai-org/GLM-5.2', name: 'GLM-5.2 (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'meta-llama/Llama-3.3-70B-Instruct', name: 'Llama 3.3 70B Instruct (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', name: 'DeepSeek R1 Distill 32B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen 2.5 72B Instruct (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'mistralai/Mistral-7B-Instruct-v0.3', name: 'Mistral 7B Instruct (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'recommended',
    badge: 'European Flagship',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    description: 'Mistral Large 3, Codestral, and Mistral Small 24B with sophisticated multilingual vocabulary.',
    defaultModel: 'mistral-large-latest',
    defaultEndpoint: 'https://api.mistral.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://console.mistral.ai/api-keys',
    freeTierInfo: 'Free experiment tier available.',
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large 3 (Best Performance)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'codestral-latest', name: 'Codestral (Creative Engine)' },
      { id: 'mistral-small-latest', name: 'Mistral Small 24B' },
      { id: 'ministral-8b-latest', name: 'Ministral 8B' },
      { id: 'ministral-3b-latest', name: 'Ministral 3B' },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'recommended',
    badge: 'Flagship LLM Standard',
    badgeColor: 'bg-green-500/20 text-green-300 border-green-500/30',
    description: 'Direct OpenAI access with GPT-5.6 Terra, GPT-4o, o3-mini, and DALL-E 3.',
    defaultModel: 'gpt-5.6-terra',
    defaultEndpoint: 'https://api.openai.com/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://platform.openai.com/api-keys',
    freeTierInfo: 'Direct pay-as-you-go and platform access.',
    models: [
      { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra (Best Performance)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'gpt-4o', name: 'GPT-4o (Omni Multimodal • Best Performance)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini (Fast & Best Value)', badge: 'Best Value' },
      { id: 'o3-mini', name: 'o3-mini (High-speed Reasoning • Best Performance)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'o1', name: 'o1 (Deep Complex Reasoning)' },
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo' },
      { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo' },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'recommended',
    badge: 'Universal Router (:free)',
    badgeColor: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    description: 'Unified gateway routing to 200+ models with free models pool and pay-as-you-go top tiers.',
    defaultModel: 'openrouter/free',
    defaultEndpoint: 'https://openrouter.ai/api/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-or-v1-...',
    portalUrl: 'https://openrouter.ai/keys',
    freeTierInfo: 'Free models tagged with :free work without balance.',
    models: [
      { id: 'openrouter/free', name: 'OpenRouter Auto Free (Free Tier)', recommended: true, isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek/deepseek-r1:free', name: 'DeepSeek R1 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek/deepseek-chat:free', name: 'DeepSeek V3 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'google/gemini-2.0-flash-exp:free', name: 'Gemini 2.0 Flash (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet (Best Performance)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'openai/gpt-4o', name: 'GPT-4o (Best Performance)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'openai/gpt-4o-mini', name: 'GPT-4o Mini (Best Value)', badge: 'Best Value' },
    ],
  },
  {
    id: 'pollinations',
    name: 'Pollinations.ai',
    category: 'recommended',
    badge: '100% Free (Open Models)',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    description: 'Fast, unlimited free tier with OpenAI GPT-4o, DeepSeek R1, Mistral Large, and Nano Banana graphics.',
    defaultModel: 'openai',
    defaultEndpoint: 'https://gen.pollinations.ai/v1',
    requiresKey: false,
    keyPlaceholder: 'Anonymous / optional key',
    portalUrl: 'https://pollinations.ai',
    freeTierInfo: 'Open community endpoints with instant access. No API key required.',
    models: [
      { id: 'openai', name: 'OpenAI GPT-4o (100% Free Tier)', recommended: true, isFreeTier: true, badge: 'Free Tier' },
      { id: 'openai-fast', name: 'OpenAI Fast (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'openai-large', name: 'OpenAI Large (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek', name: 'DeepSeek R1 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek-v3', name: 'DeepSeek V3 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'mistral', name: 'Mistral Large (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'qwen-coder', name: 'Qwen Coder (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'claude-hybrid', name: 'Claude Hybrid (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'llama', name: 'Llama 3.3 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gemini', name: 'Gemini 2.0 Flash (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'puter',
    name: 'Puter.js AI',
    category: 'recommended',
    badge: '100% Free (No Key Required)',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    description: 'Zero API keys required. Free GPT-5.4 Nano, Claude Sonnet 5, DeepSeek R1 & Nano Banana imagery.',
    defaultModel: 'openai/gpt-5.4-nano',
    requiresKey: false,
    keyPlaceholder: 'No API key needed',
    portalUrl: 'https://puter.com',
    freeTierInfo: 'Free browser-based token pool provided by Puter platform.',
    models: [
      { id: 'openai/gpt-5.4-nano', name: 'GPT-5.4 Nano (100% Free Tier)', recommended: true, isFreeTier: true, badge: 'Free Tier' },
      { id: 'anthropic/claude-sonnet-5', name: 'Claude Sonnet 5 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'google/gemini-3.1-pro-preview', name: 'Gemini 3.1 Pro (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'x-ai/grok-4.5', name: 'Grok 4.5 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'claude-3-haiku', name: 'Claude 3 Haiku (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gpt-4o', name: 'GPT-4o (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek-chat', name: 'DeepSeek V3 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'deepseek-reasoner', name: 'DeepSeek R1 (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gemini-2.0-flash', name: 'Gemini 2.0 Flash (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'mistral-large-latest', name: 'Mistral Large (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'qwen-2.5-72b-instruct', name: 'Qwen 2.5 72B (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'gemma-2-9b-it', name: 'Gemma 2 9B (100% Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    category: 'recommended',
    badge: '20M Free Tokens Pool',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    description: 'High-performance model hub hosting DeepSeek V3, DeepSeek R1, and Qwen 2.5 with 20M free tokens.',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    defaultEndpoint: 'https://api.siliconflow.cn/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://cloud.siliconflow.cn/account/ak',
    freeTierInfo: '20M free tokens for open-source models on sign-up.',
    models: [
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3 (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1 (Best Reasoning • Free Tier)', isBestPerformance: true, isFreeTier: true, badge: 'Best Reasoning • Free Tier' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen 2.5 72B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'Qwen/Qwen2.5-32B-Instruct', name: 'Qwen 2.5 32B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'meta-llama/Meta-Llama-3.1-70B-Instruct', name: 'Llama 3.1 70B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'THUDM/glm-4-9b-chat', name: 'GLM-4 9B (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'z_ai',
    name: 'Z.AI (Zhipu AI)',
    category: 'recommended',
    badge: 'Free Tier (GLM-4-Flash)',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    description: 'GLM-5.2, GLM-4 Flash, and GLM-4 Plus for instant inference and CogView visual synthesis.',
    defaultModel: 'glm-5.2',
    defaultEndpoint: 'https://api.z.ai/api/paas/v4',
    requiresKey: true,
    keyPlaceholder: 'zai-...',
    portalUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    freeTierInfo: 'GLM-4-Flash has an always-free unlimited tier.',
    models: [
      { id: 'glm-5.2', name: 'GLM-5.2 (Best Performance)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'glm-4-flash', name: 'GLM-4 Flash (100% Free Tier Fast)', isFreeTier: true, badge: 'Free Tier' },
      { id: 'glm-4-plus', name: 'GLM-4 Plus (Flagship Best Performance)', isBestPerformance: true, badge: 'Best Performance' },
      { id: 'glm-4-air', name: 'GLM-4 Air' },
      { id: 'glm-4-long', name: 'GLM-4 Long (1M Context)' },
    ],
  },
];

// 2. Image & Template Generation APIs (Alphabetically Sorted)
export const IMG_GEN_PROVIDERS: ProviderDefinition[] = [
  // --- Automation, Banner & Document Template APIs ---
  {
    id: 'abyssale',
    name: 'Abyssale',
    category: 'img_gen',
    badge: 'Multi-Channel Banners',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    description: 'Dynamic banner generation, multi-format advertising sets, and design automation.',
    defaultModel: 'banner-set-v1',
    defaultEndpoint: 'https://api.abyssale.com/v1',
    requiresKey: true,
    keyPlaceholder: 'aby_...',
    portalUrl: 'https://abyssale.com',
    startingPrice: '$15/mo',
    freeTierInfo: '14-day trial (30 credits)',
    apiType: 'Async / REST',
    regions: 'Global CDN',
    isImageGen: true,
    models: [
      { id: 'banner-set-v1', name: 'Abyssale Multi-Format Banner Set', recommended: true },
      { id: 'single-image-v1', name: 'Abyssale Single Dynamic Asset' },
    ],
  },
  {
    id: 'apitemplate',
    name: 'APITemplate.io',
    category: 'img_gen',
    badge: 'PDF + Image Automation',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Automate images and PDFs using visual drag-and-drop templates with JSON API.',
    defaultModel: 'template-render',
    defaultEndpoint: 'https://rest.apitemplate.io/v2',
    requiresKey: true,
    keyPlaceholder: 'api_key_...',
    portalUrl: 'https://apitemplate.io',
    startingPrice: '$29/mo (annual)',
    freeTierInfo: '50/mo free tier',
    apiType: 'Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'template-render', name: 'APITemplate Dynamic Image Renderer', recommended: true, isFreeTier: true, badge: 'Free Tier (50/mo)' },
      { id: 'pdf-render', name: 'APITemplate PDF Generator' },
    ],
  },
  {
    id: 'bannerbear',
    name: 'Bannerbear',
    category: 'img_gen',
    badge: 'Video + Image Workflows',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Automate social media visuals, dynamic banners, and video workflows with template REST API.',
    defaultModel: 'image-v2',
    defaultEndpoint: 'https://api.bannerbear.com/v2',
    requiresKey: true,
    keyPlaceholder: 'bb_pr_...',
    portalUrl: 'https://www.bannerbear.com',
    startingPrice: '$49/mo',
    freeTierInfo: '30 free trial credits',
    apiType: 'Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'image-v2', name: 'Bannerbear Template Image Renderer', recommended: true },
      { id: 'video-v2', name: 'Bannerbear Animated Video Generator' },
    ],
  },
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    category: 'img_gen',
    badge: 'Image CDN + Transforms',
    badgeColor: 'bg-sky-500/20 text-sky-300 border-sky-500/30',
    description: 'Enterprise image CDN, dynamic URL-based image transformations, generative fill, and effects.',
    defaultModel: 'url-transform',
    defaultEndpoint: 'https://api.cloudinary.com/v1_1/{cloud_name}',
    requiresKey: true,
    keyPlaceholder: 'Cloudinary API Key & Secret',
    portalUrl: 'https://cloudinary.com/console',
    startingPrice: '$99/mo',
    freeTierInfo: '25 credits / mo always free',
    apiType: 'URL-based',
    regions: 'Global CDN',
    isImageGen: true,
    models: [
      { id: 'url-transform', name: 'Cloudinary URL-Based Smart Crop & Transform', recommended: true, isFreeTier: true, badge: 'Free Tier' },
      { id: 'gen-fill', name: 'Cloudinary Generative AI Fill & Extend' },
    ],
  },
  {
    id: 'creatomate',
    name: 'Creatomate',
    category: 'img_gen',
    badge: 'Video-First Teams',
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    description: 'Automated video & image generation platform with timeline template editor and REST API.',
    defaultModel: 'render-v1',
    defaultEndpoint: 'https://api.creatomate.com/v1',
    requiresKey: true,
    keyPlaceholder: 'api_key_...',
    portalUrl: 'https://creatomate.com',
    startingPrice: '$54/mo',
    freeTierInfo: '50 free trial credits',
    apiType: 'Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'render-v1', name: 'Creatomate High-Speed Render Engine', recommended: true },
    ],
  },
  {
    id: 'dynapictures',
    name: 'DynaPictures',
    category: 'img_gen',
    badge: 'High-Speed Banners',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'Dynamic image generation API for e-commerce, real estate, and automated social banners.',
    defaultModel: 'dynamic-image',
    defaultEndpoint: 'https://api.dynapictures.com/v1',
    requiresKey: true,
    keyPlaceholder: 'dp_key_...',
    portalUrl: 'https://dynapictures.com',
    startingPrice: '$29/mo',
    freeTierInfo: '14-day free trial',
    apiType: 'Sync',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'dynamic-image', name: 'DynaPictures Instant Template Renderer', recommended: true },
    ],
  },
  {
    id: 'htmlcsstoimage',
    name: 'HTML/CSS to Image',
    category: 'img_gen',
    badge: 'Direct HTML Rendering',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    description: 'Convert raw HTML/CSS strings or URLs directly into high-res PNG/JPEG images via headless Chrome.',
    defaultModel: 'html-to-image-v1',
    defaultEndpoint: 'https://hcti.io/v1/image',
    requiresKey: true,
    keyPlaceholder: 'User ID & API Key',
    portalUrl: 'https://htmlcsstoimage.com',
    startingPrice: '$7/mo',
    freeTierInfo: '50/mo free tier (no watermark)',
    apiType: 'Sync',
    regions: 'Global CDN',
    isImageGen: true,
    models: [
      { id: 'html-to-image-v1', name: 'Chromium High-DPI HTML/CSS Renderer', recommended: true, isFreeTier: true, badge: 'Free Tier (50/mo)' },
    ],
  },
  {
    id: 'imejis',
    name: 'Imejis.io',
    category: 'img_gen',
    badge: 'Template-Based Generation',
    badgeColor: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    description: 'Scalable cloud template image rendering across 4 distributed edge regions.',
    defaultModel: 'template-gen-v1',
    defaultEndpoint: 'https://api.imejis.io/v1',
    requiresKey: true,
    keyPlaceholder: 'imejis_key_...',
    portalUrl: 'https://imejis.io',
    startingPrice: '$14.99/mo',
    freeTierInfo: '100 images / mo free tier',
    apiType: 'Sync',
    regions: 4,
    isImageGen: true,
    models: [
      { id: 'template-gen-v1', name: 'Imejis Cloud Template Renderer', recommended: true, isFreeTier: true, badge: 'Free Tier (100/mo)' },
    ],
  },
  {
    id: 'okzest',
    name: 'OKZest',
    category: 'img_gen',
    badge: 'Email Personalization',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    description: 'Personalized images for dynamic emails and marketing funnels in real-time.',
    defaultModel: 'email-personalized-image',
    defaultEndpoint: 'https://api.okzest.com/v1',
    requiresKey: true,
    keyPlaceholder: 'okz_key_...',
    portalUrl: 'https://okzest.com',
    startingPrice: '$12/mo',
    freeTierInfo: '2,500/mo (Watermarked free tier)',
    apiType: 'URL-based',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'email-personalized-image', name: 'OKZest Personalized Image Renderer', recommended: true, isFreeTier: true, badge: 'Free Tier (2.5K/mo)' },
    ],
  },
  {
    id: 'pictify',
    name: 'Pictify.io',
    category: 'img_gen',
    badge: 'Certificates & Reports',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    description: 'Automated certificates, dynamic documents, social cards, and report generator.',
    defaultModel: 'pictify-v1',
    defaultEndpoint: 'https://api.pictify.io/image',
    requiresKey: true,
    keyPlaceholder: 'pic_key_...',
    portalUrl: 'https://pictify.io',
    startingPrice: '$19/mo',
    freeTierInfo: '50/mo free tier (no watermark)',
    apiType: 'Sync / Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'pictify-v1', name: 'Pictify Smart Template Engine', recommended: true, isFreeTier: true, badge: 'Free Tier (50/mo)' },
    ],
  },
  {
    id: 'placid',
    name: 'Placid',
    category: 'img_gen',
    badge: 'No-Code Marketing',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    description: 'Dynamic image and PDF generation with Zapier, Make, and Airtable no-code integrations.',
    defaultModel: 'placid-v1',
    defaultEndpoint: 'https://api.placid.app/api/rest',
    requiresKey: true,
    keyPlaceholder: 'placid_token_...',
    portalUrl: 'https://placid.app',
    startingPrice: '$19/mo',
    freeTierInfo: 'Trial only',
    apiType: 'Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'placid-v1', name: 'Placid Template Engine', recommended: true },
    ],
  },
  {
    id: 'renderform',
    name: 'RenderForm',
    category: 'img_gen',
    badge: 'High-Volume Automation',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    description: 'High-volume image rendering, visual template editor, PDF, and dynamic URL generation.',
    defaultModel: 'renderform-v1',
    defaultEndpoint: 'https://get.renderform.io/api/v2/render',
    requiresKey: true,
    keyPlaceholder: 'rf_key_...',
    portalUrl: 'https://renderform.io',
    startingPrice: '$9/mo',
    freeTierInfo: '50 trial credits',
    apiType: 'Sync / URL',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'renderform-v1', name: 'RenderForm Dynamic Template Renderer', recommended: true },
    ],
  },
  {
    id: 'robolly',
    name: 'Robolly',
    category: 'img_gen',
    badge: 'Social Media Automation',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    description: 'Template-based dynamic graphics, social banners, and multi-render pipelines.',
    defaultModel: 'robolly-v1',
    defaultEndpoint: 'https://api.robolly.com/v1',
    requiresKey: true,
    keyPlaceholder: 'rob_key_...',
    portalUrl: 'https://robolly.com',
    startingPrice: '$29/mo',
    freeTierInfo: 'Free trial available',
    apiType: 'URL / REST',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'robolly-v1', name: 'Robolly Dynamic Asset Engine', recommended: true },
    ],
  },
  {
    id: 'switchboard',
    name: 'Switchboard Canvas',
    category: 'img_gen',
    badge: 'Multi-Size Responsive',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    description: 'Responsive canvas templates that automatically render across all social aspect ratios simultaneously.',
    defaultModel: 'switchboard-v1',
    defaultEndpoint: 'https://api.switchboard.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'sb_key_...',
    portalUrl: 'https://switchboard.ai',
    startingPrice: '$19/mo',
    freeTierInfo: '14-day free trial',
    apiType: 'Sync / Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'switchboard-v1', name: 'Switchboard Multi-Size Canvas', recommended: true },
    ],
  },
  {
    id: 'templated',
    name: 'Templated.io',
    category: 'img_gen',
    badge: 'Canva & Multi-Format',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Import Canva designs, customize with REST API, and render high-res marketing images.',
    defaultModel: 'templated-v1',
    defaultEndpoint: 'https://api.templated.io/v1/render',
    requiresKey: true,
    keyPlaceholder: 'templated_key_...',
    portalUrl: 'https://templated.io',
    startingPrice: '$29/mo (annual)',
    freeTierInfo: '100 images / mo free tier',
    apiType: 'Sync / Async',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'templated-v1', name: 'Templated.io Multi-Format Engine', recommended: true, isFreeTier: true, badge: 'Free Tier (100/mo)' },
    ],
  },

  // --- AI Diffusion & Neural Image Models ---
  {
    id: 'cloudflare_img',
    name: 'Cloudflare Workers AI (Flux.1)',
    category: 'img_gen',
    badge: '10K Neurons/Day Free',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Black Forest Labs FLUX.1 Schnell running serverless on Cloudflare Edge GPUs.',
    defaultModel: '@cf/black-forest-labs/flux-1-schnell',
    defaultEndpoint: 'https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1',
    requiresKey: true,
    keyPlaceholder: 'Cloudflare API Token',
    portalUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    startingPrice: 'Free (10K Neurons/Day)',
    freeTierInfo: '10,000 Neurons per day free tier',
    apiType: 'Sync REST',
    regions: 'Global Edge',
    isImageGen: true,
    models: [
      { id: '@cf/black-forest-labs/flux-1-schnell', name: 'FLUX.1 Schnell (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: '@cf/stabilityai/stable-diffusion-xl-base-1.0', name: 'SDXL Base 1.0 (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'deepinfra_img',
    name: 'DeepInfra Image',
    category: 'img_gen',
    badge: 'Lowest Bulk Cost',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    description: 'Serverless bulk operations for FLUX.1 Schnell, FLUX.1 Dev, and SDXL from $0.0005/image.',
    defaultModel: 'black-forest-labs/FLUX.1-schnell',
    defaultEndpoint: 'https://api.deepinfra.com/v1/inference',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://deepinfra.com/dash/api_keys',
    startingPrice: '~$0.0005 to $0.0019/img',
    freeTierInfo: '$1.80 initial sign-up credit',
    apiType: 'OpenAI-Compatible REST',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell (Ultra Fast & Cheap)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'black-forest-labs/FLUX.1-dev', name: 'FLUX.1 Dev (Maximum Quality)' },
      { id: 'stabilityai/sdxl-turbo', name: 'SDXL Turbo' },
    ],
  },
  {
    id: 'fal_ai',
    name: 'fal.ai',
    category: 'img_gen',
    badge: 'Real-Time Diffusion',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'Sub-second real-time inference for FLUX.1, Recraft, AuraFlow, and video diffusion models.',
    defaultModel: 'fal-ai/flux/schnell',
    defaultEndpoint: 'https://fal.run',
    requiresKey: true,
    keyPlaceholder: 'fal_key_...',
    portalUrl: 'https://fal.ai/dashboard/keys',
    startingPrice: '~$0.003 to $0.04/img',
    freeTierInfo: '$1.00 - $10.00 trial credits',
    apiType: 'Python / JS / Webhooks',
    regions: 'Distributed GPU',
    isImageGen: true,
    models: [
      { id: 'fal-ai/flux/schnell', name: 'FLUX.1 Schnell (Fast Real-Time)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'fal-ai/flux/dev', name: 'FLUX.1 Dev (Pro Visual Quality)' },
      { id: 'fal-ai/recraft-v3', name: 'Recraft v3 (Graphic & Vector Art)' },
    ],
  },
  {
    id: 'gemini_img',
    name: 'Google AI Studio (Gemini / Imagen 4)',
    category: 'img_gen',
    badge: 'Default • Photorealism',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Imagen 4 and Gemini 2.5 Flash image generation with deep scene context awareness.',
    defaultModel: 'imagen-4',
    defaultEndpoint: 'https://generativelanguage.googleapis.com/v1beta',
    requiresKey: true,
    keyPlaceholder: 'AIzaSy...',
    portalUrl: 'https://aistudio.google.com/app/apikey',
    startingPrice: 'Free (1K RPD) / Pay-as-you-go',
    freeTierInfo: '1,000 requests per day free on Gemini Flash tier',
    apiType: 'Google GenAI SDK',
    regions: 'Global Google Edge',
    isImageGen: true,
    models: [
      { id: 'imagen-4', name: 'Google Imagen 4 (Best Performance • Deep Prompt Nuance)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'gemini-2.5-flash-image', name: 'Gemini 2.5 Flash Image (Fast Scene Synthesis • Free Tier)', isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'imagen-3.0-generate-002', name: 'Imagen 3 (Standard)' },
    ],
  },
  {
    id: 'huggingface_img',
    name: 'Hugging Face Inference',
    category: 'img_gen',
    badge: 'Serverless Free Tier',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    description: 'Serverless community endpoints for FLUX.1-schnell and Stable Diffusion 3.5.',
    defaultModel: 'black-forest-labs/FLUX.1-schnell',
    defaultEndpoint: 'https://api-inference.huggingface.co/models',
    requiresKey: true,
    keyPlaceholder: 'hf_...',
    portalUrl: 'https://huggingface.co/settings/tokens',
    startingPrice: 'Free (Rate-limited)',
    freeTierInfo: '1,000 requests/day community free tier',
    apiType: 'HF Inference Client',
    regions: 'Cloud',
    isImageGen: true,
    models: [
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'stabilityai/stable-diffusion-3.5-large', name: 'Stable Diffusion 3.5 Large (Free Tier)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'openai_dalle',
    name: 'OpenAI (DALL-E 3)',
    category: 'img_gen',
    badge: 'Typographic Detail',
    badgeColor: 'bg-green-500/20 text-green-300 border-green-500/30',
    description: 'DALL-E 3 with complex prompt adherence, high detail 1024x1024 / 1792x1024 rendering.',
    defaultModel: 'dall-e-3',
    defaultEndpoint: 'https://api.openai.com/v1/images/generations',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://platform.openai.com/api-keys',
    startingPrice: '~$0.040 to $0.080/img',
    freeTierInfo: 'Paid only via OpenAI platform credit',
    apiType: 'Official OpenAI SDK',
    regions: 'Global',
    isImageGen: true,
    models: [
      { id: 'dall-e-3', name: 'DALL-E 3 (Best Typographic Accuracy)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'dall-e-2', name: 'DALL-E 2 (Fast 512x512)' },
    ],
  },
  {
    id: 'pollinations_img',
    name: 'Pollinations.ai Image',
    category: 'img_gen',
    badge: '100% Free (No Key)',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    description: '100% free open-source image generation running Nano Banana, FLUX.1, and SDXL.',
    defaultModel: 'flux',
    defaultEndpoint: 'https://image.pollinations.ai/prompt',
    requiresKey: false,
    keyPlaceholder: 'No API key needed',
    portalUrl: 'https://pollinations.ai',
    startingPrice: '100% Free',
    freeTierInfo: 'Unlimited free community GPU generation',
    apiType: 'Instant URL / REST',
    regions: 'Global',
    isImageGen: true,
    models: [
      { id: 'flux', name: 'FLUX.1 (Best Performance • 100% Free)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'turbo', name: 'SDXL Turbo (Instant • 100% Free)', isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'puter_img',
    name: 'Puter.js AI Image',
    category: 'img_gen',
    badge: '100% Free In-Browser',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    description: 'In-browser zero-key FLUX and Nano Banana image generation powered by Puter platform.',
    defaultModel: 'flux',
    requiresKey: false,
    keyPlaceholder: 'No API key needed',
    portalUrl: 'https://puter.com',
    startingPrice: '100% Free',
    freeTierInfo: 'Free browser-based token pool provided by Puter',
    apiType: 'JavaScript SDK',
    regions: 'Browser Native',
    isImageGen: true,
    models: [
      { id: 'flux', name: 'Puter FLUX.1 (100% Free Tier)', recommended: true, isFreeTier: true, badge: 'Free Tier' },
    ],
  },
  {
    id: 'recraft',
    name: 'Recraft.ai',
    category: 'img_gen',
    badge: 'True Vector (SVG) & Raster',
    badgeColor: 'bg-rose-500/20 text-rose-300 border-rose-500/30',
    description: 'World-leading AI graphic design model generating true vector SVG art and brand-consistent illustrations.',
    defaultModel: 'recraft-v3',
    defaultEndpoint: 'https://external.api.recraft.ai/v1/images/generations',
    requiresKey: true,
    keyPlaceholder: 'recraft_key_...',
    portalUrl: 'https://www.recraft.ai',
    startingPrice: '~$0.035 (Raster) / $0.08 (Vector)',
    freeTierInfo: 'Free web tier / paid API',
    apiType: 'REST API',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'recraft-v3', name: 'Recraft v3 (Best Performance • Vector & Raster)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'recraft-20b', name: 'Recraft 20B Vector Specialist' },
    ],
  },
  {
    id: 'replicate',
    name: 'Replicate',
    category: 'img_gen',
    badge: 'Open-Source Ecosystem',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Run thousands of open-source diffusion models, SDXL LoRAs, and ControlNets with one API.',
    defaultModel: 'black-forest-labs/flux-schnell',
    defaultEndpoint: 'https://api.replicate.com/v1/predictions',
    requiresKey: true,
    keyPlaceholder: 'r8_...',
    portalUrl: 'https://replicate.com/account/api-tokens',
    startingPrice: '~$0.003 to $0.04/img',
    freeTierInfo: 'Small free trial per hardware instance',
    apiType: 'Async Webhook / Polling',
    regions: 'Cloud GPUs',
    isImageGen: true,
    models: [
      { id: 'black-forest-labs/flux-schnell', name: 'FLUX.1 Schnell (Replicate Fast)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'black-forest-labs/flux-dev', name: 'FLUX.1 Dev' },
      { id: 'stability-ai/sdxl', name: 'SDXL Base' },
    ],
  },
  {
    id: 'siliconflow_img',
    name: 'SiliconFlow Image',
    category: 'img_gen',
    badge: '20M Free Tokens',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    description: 'High-speed FLUX.1-schnell and FLUX.1-dev inference on dedicated high-memory GPUs.',
    defaultModel: 'black-forest-labs/FLUX.1-schnell',
    defaultEndpoint: 'https://api.siliconflow.cn/v1/images/generations',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://cloud.siliconflow.cn/account/ak',
    startingPrice: 'Free (20M Tokens) / Low PayG',
    freeTierInfo: '20M free tokens pool for open models',
    apiType: 'OpenAI-Compatible REST',
    regions: 1,
    isImageGen: true,
    models: [
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell (Best Performance • Free Tier)', recommended: true, isBestPerformance: true, isFreeTier: true, badge: 'Best Performance • Free Tier' },
      { id: 'black-forest-labs/FLUX.1-dev', name: 'FLUX.1 Dev' },
    ],
  },
  {
    id: 'together_img',
    name: 'Together AI Image',
    category: 'img_gen',
    badge: 'High-Speed Cloud',
    badgeColor: 'bg-blue-600/20 text-blue-300 border-blue-500/30',
    description: 'Ultra-fast inference for FLUX.1 Schnell, FLUX.1 Dev, and Stable Diffusion 3.',
    defaultModel: 'black-forest-labs/FLUX.1-schnell',
    defaultEndpoint: 'https://api.together.xyz/v1/images/generations',
    requiresKey: true,
    keyPlaceholder: 'tog_...',
    portalUrl: 'https://api.together.xyz/settings/api-keys',
    startingPrice: '~$0.0019 to $0.025/img',
    freeTierInfo: 'Trial balance on account creation',
    apiType: 'Python / JS / REST',
    regions: 'Cloud',
    isImageGen: true,
    models: [
      { id: 'black-forest-labs/FLUX.1-schnell', name: 'FLUX.1 Schnell (Together High Speed)', recommended: true, isBestPerformance: true, badge: 'Best Performance' },
      { id: 'black-forest-labs/FLUX.1-dev', name: 'FLUX.1 Dev' },
      { id: 'stabilityai/stable-diffusion-3-medium', name: 'Stable Diffusion 3 Medium' },
    ],
  },
];

// 3. High-Speed Cloud Providers (Alphabetically Sorted)
export const CLOUD_PROVIDERS: ProviderDefinition[] = [
  {
    id: 'alibaba',
    name: 'Alibaba (Qwen)',
    category: 'cloud',
    badge: 'Qwen Flagship',
    badgeColor: 'bg-amber-600/20 text-amber-300 border-amber-500/30',
    description: 'Qwen Max, Qwen Plus, and Qwen 2.5 72B with exceptional multilingual and reasoning mastery.',
    defaultModel: 'qwen-max',
    defaultEndpoint: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://dashscope.console.aliyun.com',
    models: [
      { id: 'qwen-max', name: 'Qwen Max (Default Best)', recommended: true },
      { id: 'qwen-plus', name: 'Qwen Plus' },
      { id: 'qwen-turbo', name: 'Qwen Turbo' },
      { id: 'qwen-2.5-72b-instruct', name: 'Qwen 2.5 72B Instruct' },
    ],
  },
  {
    id: 'anthropic',
    name: 'Anthropic (Claude)',
    category: 'cloud',
    badge: 'Top Tier Literature',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Claude Sonnet 4.6, Claude 3.7 Sonnet, and Claude 3.5 Sonnet for rich creative writing and prose.',
    defaultModel: 'claude-sonnet-4-6',
    defaultEndpoint: 'https://api.anthropic.com/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-ant-...',
    portalUrl: 'https://console.anthropic.com/settings/keys',
    models: [
      { id: 'claude-sonnet-4-6', name: 'Claude Sonnet 4.6 (Default Best)', recommended: true },
      { id: 'claude-3-7-sonnet', name: 'Claude 3.7 Sonnet (Hybrid Reasoning)' },
      { id: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet' },
      { id: 'claude-3-haiku', name: 'Claude 3 Haiku (Instant Speed)' },
      { id: 'claude-3-opus', name: 'Claude 3 Opus (Maximum Depth)' },
    ],
  },
  {
    id: 'aws_bedrock',
    name: 'AWS Bedrock',
    category: 'cloud',
    badge: 'AWS Enterprise',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    description: 'Claude 3.5 Sonnet, Llama 3.3, and Amazon Nova via AWS Bedrock API gateway.',
    defaultModel: 'anthropic.claude-3-5-sonnet',
    defaultEndpoint: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    requiresKey: true,
    keyPlaceholder: 'AWS Bedrock Gateway Key',
    portalUrl: 'https://console.aws.amazon.com/bedrock',
    models: [
      { id: 'anthropic.claude-3-5-sonnet', name: 'Claude 3.5 Sonnet (Bedrock ID)', recommended: true },
      { id: 'meta.llama3-3-70b-instruct-v1:0', name: 'Llama 3.3 70B (Bedrock ID)' },
      { id: 'amazon.nova-pro-v1:0', name: 'Amazon Nova Pro' },
    ],
  },
  {
    id: 'azure_openai',
    name: 'Azure OpenAI',
    category: 'cloud',
    badge: 'Enterprise Cloud',
    badgeColor: 'bg-sky-500/20 text-sky-300 border-sky-500/30',
    description: 'Deploy GPT-4o, GPT-4o Mini, or reasoning models inside your enterprise Azure tenant.',
    defaultModel: 'gpt-4o',
    defaultEndpoint: 'https://your-resource.openai.azure.com/openai/deployments/your-deployment',
    requiresKey: true,
    keyPlaceholder: 'Azure API Key',
    portalUrl: 'https://portal.azure.com',
    models: [
      { id: 'gpt-4o', name: 'GPT-4o (Azure Deployment)', recommended: true },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini (Azure Deployment)' },
      { id: 'o3-mini', name: 'o3-mini (Azure Deployment)' },
      { id: 'custom-deployment', name: 'Custom Deployment Name' },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'cloud',
    badge: 'Command R+ Series',
    badgeColor: 'bg-teal-500/20 text-teal-300 border-teal-500/30',
    description: 'Command R+, Command R, and Aya Expanse for multilingual narrative accuracy.',
    defaultModel: 'command-r-plus-08-2024',
    defaultEndpoint: 'https://api.cohere.com/compatibility/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://dashboard.cohere.com/api-keys',
    freeTierInfo: 'Free trial keys with rate limits.',
    models: [
      { id: 'command-r-plus-08-2024', name: 'Command R+ (Default Best)', recommended: true },
      { id: 'command-r-08-2024', name: 'Command R' },
      { id: 'command-a-03-2025', name: 'Command A' },
      { id: 'aya-expanse-32b', name: 'Aya Expanse 32B' },
      { id: 'aya-expanse-8b', name: 'Aya Expanse 8B' },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    category: 'cloud',
    badge: 'Reasoning & Value',
    badgeColor: 'bg-blue-500/20 text-blue-300 border-blue-500/30',
    description: 'DeepSeek V4 Flash, DeepSeek Chat (V3), and DeepSeek Reasoner (R1) direct API.',
    defaultModel: 'deepseek-v4-flash',
    defaultEndpoint: 'https://api.deepseek.com/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://platform.deepseek.com/api_keys',
    models: [
      { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash (Default Best)', recommended: true },
      { id: 'deepseek-chat', name: 'DeepSeek Chat (V3)' },
      { id: 'deepseek-reasoner', name: 'DeepSeek Reasoner (R1)' },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' },
    ],
  },
  {
    id: 'inception',
    name: 'Inception AI',
    category: 'cloud',
    badge: '100M Free Tokens',
    badgeColor: 'bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/30',
    description: 'Official Mercury 2 reasoning engine with OpenAI-compatible streaming.',
    defaultModel: 'mercury-2',
    defaultEndpoint: 'https://api.inceptionlabs.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'sk_...',
    portalUrl: 'https://api.inceptionlabs.ai',
    freeTierInfo: '100M free tokens on sign up.',
    models: [
      { id: 'mercury-2', name: 'Mercury 2 (Default Fast Reasoning)', recommended: true },
    ],
  },
  {
    id: 'kimi',
    name: 'Moonshot (Kimi)',
    category: 'cloud',
    badge: '2M Token Context',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    description: 'Kimi K2.5 and Moonshot V1 with massive 2M token context memory for grand universe worldbuilding.',
    defaultModel: 'kimi-k2.5',
    defaultEndpoint: 'https://api.moonshot.cn/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://platform.moonshot.cn/console/api-keys',
    models: [
      { id: 'kimi-k2.5', name: 'Kimi K2.5 (Default Best)', recommended: true },
      { id: 'moonshot-v1-8k', name: 'Moonshot V1 8K' },
      { id: 'moonshot-v1-32k', name: 'Moonshot V1 32K' },
      { id: 'moonshot-v1-128k', name: 'Moonshot V1 128K' },
    ],
  },
  {
    id: 'minimax',
    name: 'MiniMax AI',
    category: 'cloud',
    badge: 'Long-Context Narratives',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'MiniMax M2.7 and abab6.5s for extensive character continuity and novel-length stories.',
    defaultModel: 'minimax-m2.7',
    defaultEndpoint: 'https://api.minimax.chat/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://api.minimax.chat',
    models: [
      { id: 'minimax-m2.7', name: 'MiniMax M2.7 (Default Best)', recommended: true },
      { id: 'abab6.5s', name: 'abab6.5s (High Speed)' },
      { id: 'abab6.5t', name: 'abab6.5t (High Context)' },
      { id: 'MiniMax-Text-01', name: 'MiniMax Text 01' },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    category: 'cloud',
    badge: 'European Flagship',
    badgeColor: 'bg-orange-500/20 text-orange-300 border-orange-500/30',
    description: 'Mistral Large 3, Codestral, and Mistral Small 24B with sophisticated multilingual vocabulary.',
    defaultModel: 'mistral-large-latest',
    defaultEndpoint: 'https://api.mistral.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://console.mistral.ai/api-keys',
    freeTierInfo: 'Free experiment tier available.',
    models: [
      { id: 'mistral-large-latest', name: 'Mistral Large 3 (Default Best)', recommended: true },
      { id: 'codestral-latest', name: 'Codestral (Creative Engine)' },
      { id: 'mistral-small-latest', name: 'Mistral Small 24B' },
      { id: 'ministral-8b-latest', name: 'Ministral 8B' },
      { id: 'ministral-3b-latest', name: 'Ministral 3B' },
    ],
  },
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'cloud',
    badge: 'Flagship LLM',
    badgeColor: 'bg-green-500/20 text-green-300 border-green-500/30',
    description: 'Direct OpenAI access with GPT-5.6 Terra, GPT-4o, o3-mini, and DALL-E 3.',
    defaultModel: 'gpt-5.6-terra',
    defaultEndpoint: 'https://api.openai.com/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://platform.openai.com/api-keys',
    models: [
      { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra (Default Best)', recommended: true },
      { id: 'gpt-4o', name: 'GPT-4o (Omni Multimodal)' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini (Fast & Affordable)' },
      { id: 'o3-mini', name: 'o3-mini (High-speed Reasoning)' },
      { id: 'o1', name: 'o1 (Deep Complex Reasoning)' },
      { id: 'gpt-4-turbo', name: 'GPT-4 Turbo' },
      { id: 'gpt-3.5-turbo', name: 'GPT-3.5 Turbo' },
    ],
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    category: 'cloud',
    badge: 'Unfiltered Wit & Depth',
    badgeColor: 'bg-red-500/20 text-red-300 border-red-500/30',
    description: 'Grok 4.3, Grok 4, and Grok 2 for dynamic, witty, and vivid plot creation.',
    defaultModel: 'grok-4.3',
    defaultEndpoint: 'https://api.x.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'xai-...',
    portalUrl: 'https://console.x.ai',
    models: [
      { id: 'grok-4.3', name: 'Grok 4.3 (Default Best)', recommended: true },
      { id: 'grok-4', name: 'Grok 4' },
      { id: 'grok-2-latest', name: 'Grok 2 Latest' },
      { id: 'grok-beta', name: 'Grok Beta' },
    ],
  },
  {
    id: 'z_ai',
    name: 'Z.AI (Zhipu AI)',
    category: 'cloud',
    badge: 'GLM Flagship',
    badgeColor: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/30',
    description: 'GLM-5.2, GLM-4 Flash, and GLM-4 Plus for instant inference and CogView visual synthesis.',
    defaultModel: 'glm-5.2',
    defaultEndpoint: 'https://api.z.ai/api/paas/v4',
    requiresKey: true,
    keyPlaceholder: 'zai-...',
    portalUrl: 'https://open.bigmodel.cn/usercenter/apikeys',
    freeTierInfo: 'GLM-4-Flash has an always-free tier.',
    models: [
      { id: 'glm-5.2', name: 'GLM-5.2 (Default Best)', recommended: true },
      { id: 'glm-4-flash', name: 'GLM-4 Flash (Free Tier Fast)' },
      { id: 'glm-4-plus', name: 'GLM-4 Plus (Flagship)' },
      { id: 'glm-4-air', name: 'GLM-4 Air' },
      { id: 'glm-4-long', name: 'GLM-4 Long (1M Context)' },
    ],
  },
];

// 3. High-Throughput Routers (Alphabetically Sorted)
export const ROUTER_PROVIDERS: ProviderDefinition[] = [
  {
    id: 'cerebras',
    name: 'Cerebras Cloud',
    category: 'router',
    badge: '1,800 tok/s Free',
    badgeColor: 'bg-purple-500/20 text-purple-300 border-purple-500/30',
    description: 'Fastest inference engine for Llama 3.3 70B and Llama 3.1 8B.',
    defaultModel: 'llama-3.3-70b',
    defaultEndpoint: 'https://api.cerebras.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'csk-...',
    portalUrl: 'https://cloud.cerebras.ai',
    freeTierInfo: 'Generous free tier with 30 RPM and instant response.',
    models: [
      { id: 'llama-3.3-70b', name: 'Llama 3.3 70B (Default Best)', recommended: true },
      { id: 'llama3.1-70b', name: 'Llama 3.1 70B' },
      { id: 'llama3.1-8b', name: 'Llama 3.1 8B Super Instant' },
    ],
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare (Workers AI)',
    category: 'router',
    badge: '10K Neurons/Day Free',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Edge-distributed AI workers running GLM-5.2, Llama 3.3 70B, and DeepSeek R1.',
    defaultModel: '@cf/zai-org/glm-5.2',
    defaultEndpoint: 'https://api.cloudflare.com/client/v4/accounts/{accountId}/ai/v1',
    requiresKey: true,
    keyPlaceholder: 'Cloudflare API Token',
    portalUrl: 'https://dash.cloudflare.com/profile/api-tokens',
    freeTierInfo: '10,000 Neurons per day free.',
    models: [
      { id: '@cf/zai-org/glm-5.2', name: 'GLM-5.2 (Default Best)', recommended: true },
      { id: '@cf/meta/llama-3.3-70b-instruct', name: 'Llama 3.3 70B' },
      { id: '@cf/deepseek-ai/deepseek-r1-distill-qwen-32b', name: 'DeepSeek R1 Distill 32B' },
      { id: '@cf/meta/llama-3.1-8b-instruct', name: 'Llama 3.1 8B Instruct' },
      { id: '@cf/mistral/mistral-7b-instruct-v0.1', name: 'Mistral 7B Instruct' },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    category: 'router',
    badge: 'Fast Specialized Router',
    badgeColor: 'bg-pink-500/20 text-pink-300 border-pink-500/30',
    description: 'Fast, compound inference for Llama 3.3 70B, DeepSeek V3, and customized LoRAs.',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    defaultEndpoint: 'https://api.fireworks.ai/inference/v1',
    requiresKey: true,
    keyPlaceholder: 'fw_...',
    portalUrl: 'https://fireworks.ai/account/api-keys',
    freeTierInfo: '$1 free developer credits on signup.',
    models: [
      { id: 'accounts/fireworks/models/llama-v3p3-70b-instruct', name: 'Llama 3.3 70B Instruct (Default Best)', recommended: true },
      { id: 'accounts/fireworks/models/deepseek-v3', name: 'DeepSeek V3' },
      { id: 'accounts/fireworks/models/deepseek-r1', name: 'DeepSeek R1' },
      { id: 'accounts/fireworks/models/qwen2p5-72b-instruct', name: 'Qwen 2.5 72B Instruct' },
    ],
  },
  {
    id: 'groq',
    name: 'Groq Cloud',
    category: 'router',
    badge: 'Ultra Fast (1K RPD Free)',
    badgeColor: 'bg-amber-500/20 text-amber-300 border-amber-500/30',
    description: 'Blazing LPU inference speeds for Llama 3.3 70B and DeepSeek R1 Distill.',
    defaultModel: 'llama-3.3-70b-versatile',
    defaultEndpoint: 'https://api.groq.com/openai/v1',
    requiresKey: true,
    keyPlaceholder: 'gsk_...',
    portalUrl: 'https://console.groq.com/keys',
    freeTierInfo: '1,000 requests per day always free.',
    models: [
      { id: 'llama-3.3-70b-versatile', name: 'Llama 3.3 70B Versatile (Default Best)', recommended: true },
      { id: 'deepseek-r1-distill-llama-70b', name: 'DeepSeek R1 Distill 70B' },
      { id: 'llama-3.1-70b-versatile', name: 'Llama 3.1 70B' },
      { id: 'llama-3.1-8b-instant', name: 'Llama 3.1 8B Instant' },
      { id: 'mixtral-8x7b-32768', name: 'Mixtral 8x7B' },
      { id: 'gemma2-9b-it', name: 'Gemma 2 9B' },
      { id: 'qwen-2.5-32b', name: 'Qwen 2.5 32B' },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'router',
    badge: 'Serverless Free Tier',
    badgeColor: 'bg-yellow-500/20 text-yellow-300 border-yellow-500/30',
    description: 'Serverless inference on Hugging Face Novita router for GLM-5.2 and Llama 3.3.',
    defaultModel: 'zai-org/GLM-5.2',
    defaultEndpoint: 'https://router.huggingface.co/novita/v1',
    requiresKey: true,
    keyPlaceholder: 'hf_...',
    portalUrl: 'https://huggingface.co/settings/tokens',
    freeTierInfo: 'Free community rate limits available.',
    models: [
      { id: 'zai-org/GLM-5.2', name: 'GLM-5.2 (Default Best)', recommended: true },
      { id: 'meta-llama/Llama-3.3-70B-Instruct', name: 'Llama 3.3 70B Instruct' },
      { id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B', name: 'DeepSeek R1 Distill 32B' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen 2.5 72B Instruct' },
      { id: 'mistralai/Mistral-7B-Instruct-v0.3', name: 'Mistral 7B Instruct' },
    ],
  },
  {
    id: 'nvidia',
    name: 'NVIDIA (NIM)',
    category: 'router',
    badge: '1K Free Credits (40 RPM)',
    badgeColor: 'bg-lime-500/20 text-lime-300 border-lime-500/30',
    description: 'NVIDIA NIM microservices hosting Llama 3.1 8B, Llama 3.3 70B, and Nemotron 70B.',
    defaultModel: 'meta/llama-3.1-8b-instruct',
    defaultEndpoint: 'https://integrate.api.nvidia.com/v1',
    requiresKey: true,
    keyPlaceholder: 'nvapi-...',
    portalUrl: 'https://build.nvidia.com',
    freeTierInfo: '1,000 free API credits on registration.',
    models: [
      { id: 'meta/llama-3.1-8b-instruct', name: 'Llama 3.1 8B Instruct (Default Best)', recommended: true },
      { id: 'meta/llama-3.3-70b-instruct', name: 'Llama 3.3 70B Instruct' },
      { id: 'nvidia/llama-3.1-nemotron-70b-instruct', name: 'Nemotron 70B Instruct' },
      { id: 'deepseek-ai/deepseek-r1', name: 'DeepSeek R1' },
      { id: 'mistralai/mistral-large-2-instruct', name: 'Mistral Large 2' },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    category: 'router',
    badge: 'Universal Router (:free)',
    badgeColor: 'bg-violet-500/20 text-violet-300 border-violet-500/30',
    description: 'Unified gateway routing to 200+ models with free models and pay-as-you-go top tiers.',
    defaultModel: 'openrouter/free',
    defaultEndpoint: 'https://openrouter.ai/api/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-or-v1-...',
    portalUrl: 'https://openrouter.ai/keys',
    freeTierInfo: 'Free models tagged with :free work without balance.',
    models: [
      { id: 'openrouter/free', name: 'OpenRouter Auto Free (Default Best)', recommended: true },
      { id: 'deepseek/deepseek-r1:free', name: 'DeepSeek R1 (100% Free)' },
      { id: 'deepseek/deepseek-chat:free', name: 'DeepSeek V3 (100% Free)' },
      { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B (100% Free)' },
      { id: 'google/gemini-2.0-flash-exp:free', name: 'Gemini 2.0 Flash (100% Free)' },
      { id: 'anthropic/claude-3.5-sonnet', name: 'Claude 3.5 Sonnet' },
      { id: 'openai/gpt-4o', name: 'GPT-4o' },
      { id: 'openai/gpt-4o-mini', name: 'GPT-4o Mini' },
    ],
  },
  {
    id: 'requesty',
    name: 'Requesty AI',
    category: 'router',
    badge: '200 RPD Free',
    badgeColor: 'bg-emerald-600/20 text-emerald-300 border-emerald-500/30',
    description: 'Smart multi-model routing with fallback resilience and caching.',
    defaultModel: 'meta-llama/llama-3.3-70b',
    defaultEndpoint: 'https://router.requesty.ai/v1',
    requiresKey: true,
    keyPlaceholder: 'rq_...',
    portalUrl: 'https://requesty.ai',
    freeTierInfo: '200 daily requests free.',
    models: [
      { id: 'meta-llama/llama-3.3-70b', name: 'Llama 3.3 70B (Default Best)', recommended: true },
      { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1' },
      { id: 'anthropic/claude-3-5-sonnet', name: 'Claude 3.5 Sonnet' },
      { id: 'openai/gpt-4o', name: 'GPT-4o' },
      { id: 'google/gemini-2.0-flash', name: 'Gemini 2.0 Flash' },
    ],
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    category: 'router',
    badge: 'DeepSeek & Qwen Free Pool',
    badgeColor: 'bg-indigo-500/20 text-indigo-300 border-indigo-500/30',
    description: 'High performance model hub hosting DeepSeek V3, DeepSeek R1, and Qwen 2.5.',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    defaultEndpoint: 'https://api.siliconflow.cn/v1',
    requiresKey: true,
    keyPlaceholder: 'sk-...',
    portalUrl: 'https://cloud.siliconflow.cn/account/ak',
    freeTierInfo: '20M free tokens for open-source models.',
    models: [
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3 (Default Best)', recommended: true },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' },
      { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen 2.5 72B' },
      { id: 'Qwen/Qwen2.5-32B-Instruct', name: 'Qwen 2.5 32B' },
      { id: 'meta-llama/Meta-Llama-3.1-70B-Instruct', name: 'Llama 3.1 70B' },
      { id: 'THUDM/glm-4-9b-chat', name: 'GLM-4 9B' },
    ],
  },
  {
    id: 'together',
    name: 'Together AI',
    category: 'router',
    badge: 'Ultra Fast Llama Turbo',
    badgeColor: 'bg-blue-600/20 text-blue-300 border-blue-500/30',
    description: 'Together AI high-throughput endpoints for Llama 3.3 70B Turbo and DeepSeek V3.',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    defaultEndpoint: 'https://api.together.xyz/v1',
    requiresKey: true,
    keyPlaceholder: 'together-...',
    portalUrl: 'https://api.together.xyz/settings/api-keys',
    freeTierInfo: 'Free credits on signup.',
    models: [
      { id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo', name: 'Llama 3.3 70B Turbo (Default Best)', recommended: true },
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3' },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' },
      { id: 'meta-llama/Llama-3.1-405B-Instruct-Turbo', name: 'Llama 3.1 405B Turbo' },
      { id: 'Qwen/Qwen2.5-72B-Instruct-Turbo', name: 'Qwen 2.5 72B Turbo' },
    ],
  },
];

// 4. Local LLMs & In-Browser (Alphabetically Sorted)
export const LOCAL_PROVIDERS: ProviderDefinition[] = [
  {
    id: 'others',
    name: 'Custom Endpoint / Reverse Proxy',
    category: 'local',
    badge: 'Any OpenAI BaseURL',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Connect any OpenAI-compatible server (e.g. text-generation-webui, FastChat, Litellm).',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    defaultEndpoint: 'https://api.openai.com/v1',
    requiresKey: true,
    keyPlaceholder: 'Custom API Key or Bearer Token',
    portalUrl: 'https://github.com/BerriAI/litellm',
    freeTierInfo: 'Connect to any private or self-hosted API gateway.',
    models: [
      { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3 (Default)', recommended: true },
      { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1' },
      { id: 'gpt-4o', name: 'GPT-4o' },
      { id: 'gpt-4o-mini', name: 'GPT-4o Mini' },
      { id: 'o3-mini', name: 'o3-mini' },
      { id: 'claude-3-5-sonnet-20241022', name: 'Claude 3.5 Sonnet' },
      { id: 'MiniMaxAI/MiniMax-M2.5', name: 'MiniMax M2.5' },
      { id: 'zai-org/GLM-5', name: 'GLM-5' },
      { id: 'stepfun-ai/Step-3.5-Flash', name: 'Step 3.5 Flash' },
      { id: 'moonshotai/Kimi-K2.5', name: 'Kimi K2.5' },
      { id: 'Qwen/Qwen3-32B', name: 'Qwen3 32B' },
    ],
  },
  {
    id: 'gpt4all',
    name: 'GPT4All (Local)',
    category: 'local',
    badge: 'Local Port 4891',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Privacy-aware desktop local LLM application with webserver on port 4891.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:4891/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional token',
    portalUrl: 'https://gpt4all.io',
    freeTierInfo: '100% Offline & Free.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'gpt4all-model', name: 'gpt4all-model' },
    ],
  },
  {
    id: 'jan',
    name: 'Jan.ai (Local)',
    category: 'local',
    badge: 'Local Port 1337',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Open-source local AI assistant with local Nitro inference server.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:1337/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional token',
    portalUrl: 'https://jan.ai',
    freeTierInfo: '100% Offline & Free.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'jan-model', name: 'jan-model' },
    ],
  },
  {
    id: 'llamacpp',
    name: 'Llama.cpp (Local)',
    category: 'local',
    badge: 'Local Port 8080',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Native C++ GGUF inference running locally on CPU/Metal/CUDA.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:8080/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional local bearer token',
    portalUrl: 'https://github.com/ggerganov/llama.cpp',
    freeTierInfo: '100% Offline & Private on your device.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'default', name: 'default' },
      { id: 'local-model', name: 'local-model' },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio (Local)',
    category: 'local',
    badge: 'Local Port 1234',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'GUI local LLM host running GGUFs with automated OpenAI-compatible server on port 1234.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:1234/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional token',
    portalUrl: 'https://lmstudio.ai',
    freeTierInfo: '100% Offline & Free.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'local-model', name: 'local-model' },
    ],
  },
  {
    id: 'local_openai_proxy',
    name: 'Local OpenAI Proxy',
    category: 'local',
    badge: 'Custom Port 5000',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Custom proxy forwarding OpenAI requests to local services or middleware.',
    defaultModel: '(required)',
    defaultEndpoint: 'http://localhost:5000/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional proxy token',
    portalUrl: 'https://github.com/openai/openai-openapi',
    freeTierInfo: 'Custom local routing.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default)', recommended: true },
      { id: 'custom-model', name: 'custom-model' },
    ],
  },
  {
    id: 'localai',
    name: 'LocalAI (Local)',
    category: 'local',
    badge: 'Local Port 8080',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Self-contained, drop-in OpenAI replacement for CPU and consumer GPUs.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:8080/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional token',
    portalUrl: 'https://localai.io',
    freeTierInfo: '100% Offline & Free.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'local-model', name: 'local-model' },
    ],
  },
  {
    id: 'ollama',
    name: 'Ollama (Local)',
    category: 'local',
    badge: 'Local Port 11434',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'One-click local model runner for Llama 3.3, DeepSeek R1, Qwen 2.5, Mistral, and Gemma 2.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:11434/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional local auth',
    portalUrl: 'https://ollama.com',
    freeTierInfo: '100% Offline & Free.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Auto via /api/show)', recommended: true },
      { id: 'llama3.3', name: 'llama3.3:latest' },
      { id: 'deepseek-r1', name: 'deepseek-r1:latest' },
      { id: 'qwen2.5', name: 'qwen2.5:latest' },
      { id: 'mistral', name: 'mistral:latest' },
      { id: 'gemma2', name: 'gemma2:latest' },
      { id: 'phi4', name: 'phi4:latest' },
    ],
  },
  {
    id: 'sglang',
    name: 'SGLang (Local / Self-Hosted)',
    category: 'local',
    badge: 'Local Port 30000',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Ultra high-speed structured generation engine for local and cluster servers.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:30000/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional SGLang API key',
    portalUrl: 'https://sglang.ai',
    freeTierInfo: 'Self-hosted & Local.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'sglang-model', name: 'sglang-model' },
    ],
  },
  {
    id: 'vllm',
    name: 'vLLM (Local / Self-Hosted)',
    category: 'local',
    badge: 'Local Port 8000',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'High-throughput PagedAttention server for self-hosted GPU clusters.',
    defaultModel: '(loaded model)',
    defaultEndpoint: 'http://localhost:8000/v1',
    requiresKey: false,
    keyPlaceholder: 'Optional vLLM API key',
    portalUrl: 'https://vllm.ai',
    freeTierInfo: 'Self-hosted & Local.',
    models: [
      { id: '(loaded model)', name: '(loaded model) (Default Auto)', recommended: true },
      { id: 'vllm-model', name: 'vllm-model' },
    ],
  },
  {
    id: 'webgpu',
    name: 'WebGPU (In-Browser / Chromium)',
    category: 'local',
    badge: 'Zero Server • WebGPU',
    badgeColor: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/30',
    description: 'Run neural networks directly in your browser tab using WebGPU acceleration & Transformers.js.',
    defaultModel: 'LFM2.5 2.6B (default)',
    requiresKey: false,
    keyPlaceholder: 'No server or key required',
    portalUrl: 'https://huggingface.co/docs/transformers.js',
    freeTierInfo: '100% Private in-browser execution.',
    models: [
      { id: 'LFM2.5 2.6B (default)', name: 'LFM2.5 2.6B (Default WebGPU)', recommended: true },
      { id: 'Bonsai 27B', name: 'Bonsai 27B (Opt-in High Capacity)' },
      { id: 'Qwen2.5-0.5B-Instruct-WebGPU', name: 'Qwen 2.5 0.5B Instruct (Ultra-light)' },
      { id: 'SmolLM2-135M-Instruct-WebGPU', name: 'SmolLM2 135M Instruct (Instant Init)' },
    ],
  },
];

// 5. Extended Provider Catalog (72 OpenCode / WebBrain cards, Alphabetically Sorted)
export const EXTENDED_PROVIDER_IDS = [
  '302ai', 'abacus', 'aihubmix', 'alibaba-coding-plan', 'alibaba-coding-plan-cn',
  'azure-cognitive-services', 'bailing', 'baseten', 'berget', 'chutes',
  'clarifai', 'cloudferro-sherlock', 'cortecs', 'deepinfra', 'digitalocean',
  'dinference', 'drun', 'evroc', 'fastrouter', 'friendli', 'google-vertex',
  'google-vertex-anthropic', 'helicone', 'iflowcn', 'inference', 'io-net',
  'jiekou', 'kilo', 'kimi-for-coding', 'kuae-cloud-coding-plan', 'llama',
  'lucidquery', 'meganova', 'minimax-cn-coding-plan', 'minimax-coding-plan',
  'moark', 'modelscope', 'morph', 'nano-gpt', 'nebius', 'nova', 'novita-ai',
  'ollama-cloud', 'opencode', 'opencode-go', 'orcarouter', 'ovhcloud',
  'perplexity', 'perplexity-agent', 'poe', 'privatemode-ai', 'qihang-ai',
  'qiniu-ai', 'scaleway', 'siliconflow-cn', 'stackit', 'stepfun', 'submodel',
  'synthetic', 'tencent-coding-plan', 'upstage', 'v0', 'venice', 'vercel',
  'vivgrid', 'vultr', 'wandb', 'xiaomi', 'zai-coding-plan', 'zenmux',
  'zhipuai', 'zhipuai-coding-plan'
] as const;

// Custom Direct Portals for Extended Providers
const EXTENDED_PORTAL_OVERRIDES: Record<string, string> = {
  '302ai': 'https://302.ai',
  'abacus': 'https://abacus.ai',
  'aihubmix': 'https://aihubmix.com',
  'baseten': 'https://baseten.co',
  'clarifai': 'https://clarifai.com',
  'deepinfra': 'https://deepinfra.com',
  'digitalocean': 'https://cloud.digitalocean.com/genai',
  'friendli': 'https://friendli.ai',
  'google-vertex': 'https://console.cloud.google.com/vertex-ai',
  'google-vertex-anthropic': 'https://console.cloud.google.com/vertex-ai',
  'helicone': 'https://helicone.ai',
  'io-net': 'https://io.net',
  'modelscope': 'https://modelscope.cn',
  'nebius': 'https://nebius.com',
  'novita-ai': 'https://novita.ai',
  'perplexity': 'https://www.perplexity.ai/settings/api',
  'perplexity-agent': 'https://www.perplexity.ai/settings/api',
  'poe': 'https://poe.com/api_key',
  'scaleway': 'https://console.scaleway.com',
  'stepfun': 'https://platform.stepfun.com',
  'upstage': 'https://console.upstage.ai',
  'v0': 'https://v0.dev',
  'venice': 'https://venice.ai',
  'vercel': 'https://vercel.com',
  'vultr': 'https://vultr.com',
  'wandb': 'https://wandb.ai',
  'zhipuai': 'https://open.bigmodel.cn',
};

export const EXTENDED_PROVIDERS: ProviderDefinition[] = [...EXTENDED_PROVIDER_IDS]
  .sort()
  .map((id) => {
    const formattedName = id
      .split('-')
      .map(s => s.charAt(0).toUpperCase() + s.slice(1))
      .join(' ');

    const portalUrl = EXTENDED_PORTAL_OVERRIDES[id] || `https://${id.replace(/-/g, '')}.com`;

    return {
      id,
      name: formattedName,
      category: 'extended',
      badge: 'Extended Catalog',
      badgeColor: 'bg-purple-900/30 text-purple-300 border-purple-700/30',
      description: `Extended catalog provider from OpenCode/WebBrain registry. OpenAI-compatible API connection.`,
      defaultModel: 'default-model',
      defaultEndpoint: `https://api.${id.replace(/-/g, '')}.com/v1`,
      requiresKey: true,
      keyPlaceholder: `${id} API Key`,
      portalUrl,
      isExtended: true,
      models: [
        { id: 'default-model', name: `${formattedName} Default Model`, recommended: true },
        { id: 'fast-model', name: `${formattedName} Fast Model` },
        { id: 'reasoning-model', name: `${formattedName} Reasoning Model` },
      ],
    };
  });

// All Providers Flat List
export const ALL_PROVIDERS: ProviderDefinition[] = [
  ...RECOMMENDED_PROVIDERS,
  ...IMG_GEN_PROVIDERS,
  ...CLOUD_PROVIDERS,
  ...ROUTER_PROVIDERS,
  ...LOCAL_PROVIDERS,
  ...EXTENDED_PROVIDERS,
];

// All Providers Alphabetically Sorted by Name
export const ALL_PROVIDERS_ALPHABETICAL: ProviderDefinition[] = (() => {
  const seen = new Set<string>();
  const list: ProviderDefinition[] = [];
  for (const prov of ALL_PROVIDERS) {
    if (!seen.has(prov.id)) {
      seen.add(prov.id);
      list.push(prov);
    }
  }
  return list.sort((a, b) => a.name.localeCompare(b.name));
})();

// Quick Lookup by Provider ID
export const PROVIDER_MAP = new Map<string, ProviderDefinition>(
  ALL_PROVIDERS.map(p => [p.id, p])
);

export function getProviderById(id: string): ProviderDefinition {
  return PROVIDER_MAP.get(id) || {
    id,
    name: id,
    category: 'extended',
    badge: 'Custom Provider',
    badgeColor: 'bg-slate-500/20 text-slate-300 border-slate-500/30',
    description: 'Custom configured provider.',
    defaultModel: 'default',
    defaultEndpoint: 'https://api.openai.com/v1',
    requiresKey: true,
    portalUrl: 'https://platform.openai.com',
    models: [{ id: 'default', name: 'Default Model', recommended: true }],
  };
}
